import type { TeamMember } from "./types";

export const teamMembers: TeamMember[] = [
  {
    id: "hazel",
    name: "Hazel",
    roleTitle: "Head Coach",
    qualifications: [],
    photoUrl: "/coaches/Hazel.jpg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I got into gymnastics at 9 years old and instantly fell in love with the sport. I began my coaching career in my early 20s and started running my own classes at 27, travelling between different sports centres. In 2015 we finally moved into our purpose-built gym. I love my work and I have such an enthusiastic team working alongside me who share that same love for the sport, which I feel shows in our classes and in the care we give to every gymnast who comes through our doors.",
  },
  {
    id: "karen",
    name: "Karen",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Karen.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I got into gymnastics coaching through my daughter, who has been a competitive gymnast since she was five. Spending so much time in the gym, I developed a real appreciation for the sport and the dedication it takes, which naturally led me to get involved in coaching. I genuinely enjoy helping children develop their skills and confidence, and I am constantly learning from everyone in the gym, both gymnasts and fellow coaches. It is a great environment to be part of, and what makes it even more special is the club itself: fun, caring, and full of hardworking people who support each other every step of the way.",
  },
  {
    id: "chloe",
    name: "Chloe",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Chloe.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I was first introduced to gymnastics in primary school, where my PE teacher encouraged me to join a local club. I trained competitively from ages 7 to 13, and although I stopped competing, my passion for the sport continued. I began volunteering at 13, starting with setting up equipment and progressing to coaching young gymnasts, which is where I discovered my love for coaching. I joined Eagle Gymnastics in 2025 and have loved being part of such a supportive, family-like environment. Helping gymnasts grow in skill and confidence alongside a great team of coaches makes my role incredibly rewarding.",
  },
  {
    id: "alyson",
    name: "Alyson",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Alyson.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "Gymnastics has been a part of my life since I was five years old. My dedication to the sport earned me a place on the Scottish national squad, allowing me to proudly represent Scotland in numerous competitions. I began coaching at 16 and have continued to support young gymnasts ever since. In 2019, I also became a club judge, adding another layer of expertise to Team Eagle.",
  },
  {
    id: "faye",
    name: "Faye",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Faye.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I started gymnastics when I was younger because I was a very active child and loved doing cartwheels around the house. Since then, gymnastics has always been a huge passion of mine. I love the feeling of learning new skills and working hard. I have grown up training at Eagle Gymnastics Academy and it has become my second home, spending multiple days each week in the gym surrounded by friends and coaches. Everyone in the gym is so welcoming and it really feels like one big family. As my passion for the sport grew, I wanted to help other gymnasts in the same way my coaches helped me, so I decided to start coaching. Ever since then, I have loved working with gymnasts and seeing them progress.",
  },
  {
    id: "jane",
    name: "Jane",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Jane.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I have been part of Eagle Gymnastics since I was 7 years old, first as a gymnast and now as a coach. My favourite part about coaching is helping children succeed and progress in gymnastics while making sure they are having fun at the same time.",
  },
  {
    id: "shannon",
    name: "Shannon",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Shannon.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I started my gymnastics journey at this club as a young gymnast, which is where my passion for the sport began. I went on to study sport at college, achieving an HND in Sports Coaching and Development, and I am currently studying Sports Business Management at university. Alongside my studies, I coach twice a week and hold a Level 2 Women's Artistic Gymnastics qualification. I am passionate about creating a safe and inclusive environment where children of all abilities can develop their skills, build confidence, and get the most out of my coaching.",
  },
  {
    id: "natascha",
    name: "Natascha",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Natascha.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I started gymnastics when I was 9 after my mum's friend recommended Eagle Gymnastics Academy. I am now 19 and have been training here ever since. I have been a helper for the past couple of years and I really enjoy seeing young gymnasts grow a passion for gymnastics. This gym has been a huge part of my life for over a decade and it has always been a very supportive and friendly environment to be part of.",
  },
  {
    id: "lilymay",
    name: "Lilymay",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Lilymay.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I got into gymnastics through my cousin Alexis and joined her recreational classes. When I was 12, Hazel asked if I would be interested in coaching and I said yes. Even though I do not take those recreational classes anymore, I still love working for Hazel and being part of Eagle Gymnastics. You learn a lot here and pick up different techniques from different people until you find what works for you. The team is so supportive, and my favourite thing about Eagle Gymnastics is probably the people. It is a great environment to be around, whether you are learning or just having a good laugh.",
  },
  {
    id: "megan",
    name: "Megan",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Megan.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I was a competitive gymnast and part of the Scottish National Squad for nearly a decade. Gymnastics has given me invaluable skills and experience which I take into every aspect of my life. I was lucky enough to compete internationally for Scotland, visiting countries such as Russia, Sweden, and America. My journey started with Hazel in 2008 in Renfrew Sports Centre. I attended her gymnastics classes and fell in love with the sport. I know first-hand how much gymnastics has made a positive impact on my life, which is why I am passionate about coaching the younger generation. Eagle is a club where gymnastics is made fun and accessible to all abilities. Hazel has created a community for gymnastics, welcoming children from all over Renfrewshire to grow, learn, and love the sport as much as we do.",
  },
  {
    id: "kara",
    name: "Kara",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Kara.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I have been at Eagle Gymnastics since I was 9 and that is how I got into coaching. My favourite part about coaching is building relationships with the gymnasts and watching them progress and get better over time.",
  },
  {
    id: "olivia",
    name: "Olivia",
    roleTitle: "Coach",
    qualifications: [],
    photoUrl: "/coaches/Olivia.jpeg",
    imageWidth: 1179,
    imageHeight: 1193,
    bio: "I first joined Eagles as a gymnast, not as a coach. Eagles gave me the opportunity to begin doing something I never knew I'd love so much. My favourite thing about Eagles is how we're all like a family. It's more than just teaching gymnasts, it's building relationships with the gymnasts.",
  },
];
